### ISSUE TITLE
Missing Instructions for Setting Up Environment Variables 

### ISSUE THREAD

**Issue by Vipul-Vermaa** [thezeeshann/real-time-chat-video#7]
The README file does not provide instructions for setting up the environment variables required for the project to function correctly. There are no steps or guidance on how to create a .env file or which specific values need to be added.

**Comment by thezeeshann** [comment]
@Vipul-Vermaa then update the readme

**Comment by Vipul-Vermaa** [comment]
assign it to me..

**Comment by Vipul-Vermaa** [comment]
> @Vipul-Vermaa then update the readme

I have open a pull request for this
